### ISSUE TITLE
ExplorerPatcher

### ISSUE THREAD

**Issue by Metal-Tom** [valinet/valinet#1]
Hi
Is it anyhow possible, to add the Widgets from W11 to the "replaced" Taskbar?

**Comment by valinet** [comment]
Please open issues in "ExplorerPatcher", not here. Also, there is this option which adds a widget button to the taskbar:

![image](https://user-images.githubusercontent.com/6503598/139520019-94a96b53-b385-4a5f-add4-adaf9f29952a.png)

**Comment by Metal-Tom** [comment]
![valinet](https://user-images.githubusercontent.com/44736926/139954650-f0e89381-8d92-4953-ac9d-828155bd9b60.png)

**Comment by valinet** [comment]
https://github.com/valinet/ExplorerPatcher/releases/tag/22000.282.32

**Comment by valinet** [comment]
Even that changed, now it looks like this:

![image](https://user-images.githubusercontent.com/6503598/139955052-5fde1975-e609-4be5-9fcf-56fe70dfb5bc.png)

What I sent is the current pre-release version which will become the actual release at some point, otherwise, check out the source and compile and you always have the bleeding edge.
